version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:v0.32.0
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'hedera-testnet:https://testnet.hashio.io/api'
      GRAPH_LOG: info
  postgres:
    image: postgres:13
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    ports:
      - '5432:5432'
  ipfs:
    image: ipfs/go-ipfs:v0.12.0
    ports:
      - '5001:5001'
